// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqotqlgfigoqvnpghqrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impxb3RxbGdmaWdvcXZucGdocXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODkxOTgsImV4cCI6MjA2NDQ2NTE5OH0.YksF-fvxs6tQcFSingWaGAge8cUR0EKLJbDFPUzR_hk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);